const actionTypes = {
  //Login
  FAZER_LOGIN: 'LOGIN',
  LOGIN_REALIZADO: 'LOGIN_REALIZADO',
  FLAG_LOGIN_REALIZADO: 'FLAG_LOGIN_REALIZADO',
  FAZER_LOGOUT: 'FAZER_LOGOUT',
  LOGOUT_REALIZADO: 'LOGOUT_REALIZADO',

  //Cadastro
  FAZER_CADASTRO: 'CADASTRO',
  CADASTRO_REALIZADO: 'CADASTRO_REALIZADO',
  FLAG_CADASTRO_REALIZADO: 'FLAG_CADASTRO_REALIZADO',

  //Cardapio
  CARDAPIOS_ENCONTRADOS: 'CARDAPIOS_ENCONTRADOS',
  CATEGORIA_ENCONTRADA: 'CATEGORIA_ENCONTRADA',
  PRODUTO_ENCONTRADO: 'PRODUTO_ENCONTRADO',
  CARDAPIO_ENCONTRADO: 'CARDAPIO_ENCONTRADO',
  MELHORES_PRODUTOS_REGIAO_ENCONTRADOS: 'MELHORES_PRODUTOS_REGIAO_ENCONTRADOS',
  PRODUTOS_REGIAO_ENCONTRADOS: 'PRODUTOS_REGIAO_ENCONTRADOS',
  PRODUTOS_FILTRADOS: 'PRODUTOS_FILTRADOS',

  //Carrinho
  PEDIDOS_ENCONTRADOS: 'PEDIDOS_ENCONTRADOS',
  CARRINHO_ENCONTRADO: 'CARRINHO_ENCONTRADO',
  PRODUTO_ADICIONADO_NO_CARRINHO: 'PRODUTO_ADICIONADO_NO_CARRINHO',
  FLAG_PRODUTO_ADICIONADO_NO_CARRINHO: 'FLAG_PRODUTO_ADICIONADO_NO_CARRINHO',
  PEDIDO_GERADO: 'PEDIDO_GERADO',
  FLAG_PEDIDO_GERADO: 'FLAG_PEDIDO_GERADO',

  //Pedidos
  PEDIDO_EFETUADO: 'PEDIDO_EFETUADO',
  PEDIDOS: 'PEDIDOS',

  //Fornecedor
  FORNECEDORES_ENCONTRADOS: 'FORNECEDORES_ENCONTRADOS',
  FORNECEDORES_FILTRADOS: 'FORNECEDORES_FILTRADOS',
  FORNECEDORES_POR_CATEGORIA_FILTRADOS: 'FORNECEDORES_POR_CATEGORIA_FILTRADOS',

  //LOADER
  LOADING: 'LOADING',

  //Erros
  APRESENTAR_ERROS: 'APRESENTAR_ERROS',
};

export default actionTypes;
