const actionTypes = {
  //Login
  FAZER_LOGIN: 'LOGIN',
  LOGIN_REALIZADO: 'LOGIN_REALIZADO',
  FAZER_LOGOUT: 'FAZER_LOGOUT',
  LOGOUT_REALIZADO: 'LOGOUT_REALIZADO',

  //Cadastro
  FAZER_CADASTRO: 'CADASTRO',
  CADASTRO_REALIZADO: 'LOGIN_REALIZADO',

  //Cardapio
  CARDAPIOS_ENCONTRADOS: 'CARDAPIOS_ENCONTRADOS',
  CATEGORIA_ENCONTRADA: 'CATEGORIA_ENCONTRADA',
  PRODUTO_ENCONTRADO: 'PRODUTO_ENCONTRADO',
  CARDAPIO_ENCONTRADO: 'CARDAPIO_ENCONTRADO',
  MELHORES_PRODUTOS_REGIAO_ENCONTRADOS: 'MELHORES_PRODUTOS_REGIAO_ENCONTRADOS',
  PRODUTOS_REGIAO_ENCONTRADOS: 'PRODUTOS_REGIAO_ENCONTRADOS',

  //Carrinho
  PEDIDOS_ENCONTRADOS: 'PEDIDOS_ENCONTRADOS',
  CARRINHO_ENCONTRADO: 'CARRINHO_ENCONTRADO',
  PRODUTO_ADICIONADO_NO_CARRINHO: 'PRODUTO_ADICIONADO_NO_CARRINHO',
  PEDIDO_GERADO: 'PEDIDO_GERADO',

  //Pedidos
  PEDIDO_EFETUADO: 'PEDIDO_EFETUADO',
  PEDIDOS: 'PEDIDOS',

  //Fornecedor
  FORNECEDORES_ENCONTRADOS: 'FORNECEDORES_ENCONTRADOS',

  //LOADER
  LOADING: 'LOADING',

  //Erros
  APRESENTAR_ERROS: 'APRESENTAR_ERROS',
};

export default actionTypes;
